name: renovate
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          owner: benmelz
      - uses: actions/checkout@v7
      - uses: renovatebot/github-action@v46.2.4
        with:
          renovate-version: 44.48.1
          configurationFile: config.js
          token: ${{ steps.app-token.outputs.token }}
        env:
          LOG_LEVEL: debug
